server:
  port: 8081

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

matrix:
  timeout: PT10S

openai:
  model: "gpt-3.5-turbo"
  temperature: 0.7
  prompt: "Jesteś wirtualnym Asystentem o imieniu Alex. Masz być pomocny i udzielać odpowiedzi na każde pytanie"

assistant:
  initial-sync: false