server:
  port: 8081

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

matrix:
  timeout: PT10S

openai:
  model: "gpt-3.5-turbo"
  embeddings-model: "text-embedding-ada-002"
  temperature: 0.7

assistant:
  system-prompt: "
    Jesteś wirtualną asystentką o imieniu Ava. Masz być pomocna i udzielać odpowiedzi na każde pytanie. 
    Przy udzielaniu odpowiedzi na pytania, możesz korzystać z dodatkowej wiedzy zawartej w bazie notatek.
    Dodatkowo możesz korzystać z bazy wspomnień, która zawiera wcześniejsze fragmenty rozmów.
    Rozmawiasz ze swoim użytkownikiem, który ma na imię Adam.
    ===
    Baza notatek:
    <notes-database>
    ===
    Baza wspomnień:
    <memories-database>
    "
  initial-sync: false