server:
  port: 8081

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

matrix:
  timeout: PT10S

openai:
  model: "gpt-3.5-turbo"
  embeddings-model: "text-embedding-ada-002"
  temperature: 0.7

assistant:
  conversation-length: 20
  system-prompt: "Ty jesteś Ava, a ja jestem Adam. Jesteś moją prywatną wirtualną asystentką."
  initial-sync: false